package Presentacion;

import DataTypes.DataCliente;
import DataTypes.DataProveedor;
import DataTypes.DataUsuario;
import Interfaces.Fabrica;
import Interfaces.IAltaUsuario;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class AddUsuario extends javax.swing.JInternalFrame {

    Image image;
    File imageFile;

    public AddUsuario() {
        initComponents();
        //Maneja tamaño
        Presentacion MAIN = Presentacion.getPrincipal();
        Integer Alto = MAIN.getHeight() - 60;
        Integer Ancho = MAIN.getWidth() - 10;
        this.setPreferredSize(new Dimension(Ancho, Alto));
        //Visible
        this.setVisible(true);
        image = null;

        rdClie.setSelected(true);
        paneProve.setVisible(false);
    }

    private void MostrarMensaje(String Mensaje, String Titulo) {
        JOptionPane.showMessageDialog(this,
                Mensaje,
                Titulo,
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void doClose() {
        this.setVisible(false);
        this.hide();
        Presentacion.SwapMenu();
    }

    private boolean isEmail(String correo) {
        //Pattern pat = Pattern.compile("^([0-9a-zA-Z]([_.w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-w]*[0-9a-zA-Z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
        Pattern pat = Pattern.compile("^[0-9a-zA-Z._%+-]+@[0-9a-zA-Z.-]+\\.[0-9a-zA-Z]{2,6}$");
        Matcher mat = pat.matcher(correo);
        return mat.find();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        btnSalir = new javax.swing.JButton();
        Etiqueta = new javax.swing.JLabel();
        AddUsu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chsrDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();
        rdClie = new javax.swing.JRadioButton();
        rdProve = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtRPass = new javax.swing.JPasswordField();
        paneProve = new javax.swing.JPanel();
        txtComp = new javax.swing.JTextField();
        txtWeb = new javax.swing.JTextField();
        lblSW = new javax.swing.JLabel();
        lblCom = new javax.swing.JLabel();

        setTitle("Agregar Usuario");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        AddUsu.setText("Agregar");
        AddUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUsuActionPerformed(evt);
            }
        });

        jLabel1.setText("NickName");

        txtNick.setAutoscrolls(false);

        jLabel2.setText("Nombre");

        txtNombre.setAutoscrolls(false);

        jLabel3.setText("Apellido");

        txtApellido.setAutoscrolls(false);

        jLabel4.setText("E-Mail");

        txtMail.setAutoscrolls(false);

        jLabel5.setText("Fecha");

        chsrDate.setDate(new Date());
        chsrDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chsrDatePropertyChange(evt);
            }
        });

        jLabel6.setText("Imagen ");

        btnSelect.setText("Seleccionar");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        rdClie.setText("Cliente");
        rdClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdClieActionPerformed(evt);
            }
        });

        rdProve.setText("Proveedor");
        rdProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdProveActionPerformed(evt);
            }
        });

        jLabel7.setText("PassWord");

        txtPass.setAutoscrolls(false);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        jLabel8.setText("Re-PassWord");

        txtRPass.setAutoscrolls(false);
        txtRPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNick))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRPass)
                            .addComponent(txtPass)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chsrDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(rdClie)
                        .addGap(18, 18, 18)
                        .addComponent(rdProve)
                        .addContainerGap(88, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rdClie, rdProve});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chsrDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdProve)
                    .addComponent(rdClie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtComp.setAutoscrolls(false);

        txtWeb.setAutoscrolls(false);

        lblSW.setText("Sito Web ");

        lblCom.setText("Compañia");

        javax.swing.GroupLayout paneProveLayout = new javax.swing.GroupLayout(paneProve);
        paneProve.setLayout(paneProveLayout);
        paneProveLayout.setHorizontalGroup(
            paneProveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneProveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneProveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSW)
                    .addComponent(lblCom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(paneProveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtComp, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(txtWeb)))
        );
        paneProveLayout.setVerticalGroup(
            paneProveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneProveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneProveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSW)
                    .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneProveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCom))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 564, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneProve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddUsu))
                            .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paneProve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        doClose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed

        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            imageFile = fc.getSelectedFile();

            // image = Toolkit.getDefaultToolkit().getImage(imageFile.toString());

            Etiqueta.setText("");

            try {
                Etiqueta.setIcon(Presentacion.fixImagen(imageFile.toString(), Etiqueta));
            } catch (IOException e) {
            }
        }

    }//GEN-LAST:event_btnSelectActionPerformed

    private void rdProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdProveActionPerformed
        // TODO add your handling code here:
        rdClie.setSelected(false);
        paneProve.setVisible(true);
    }//GEN-LAST:event_rdProveActionPerformed

    private void rdClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdClieActionPerformed
        // TODO add your handling code here:
        rdProve.setSelected(false);
        paneProve.setVisible(false);
    }//GEN-LAST:event_rdClieActionPerformed

    private void AddUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUsuActionPerformed
        IAltaUsuario IAU = Fabrica.getIAU();

        boolean Correcto = true;

        //Chequeo Nickname Vacio
        if (Correcto & txtNick.getText().equals("")) {
            MostrarMensaje("Debe Ingresar un Nickname.", "Error");
            Correcto = false;
        }

        //Chequeo Password Vacio
        if (Correcto & txtPass.getText().equals("")) {
            MostrarMensaje("Debe Ingresar un PassWord.", "Error");
            Correcto = false;
        }

        //Chequeo Password Coincide
        if (Correcto & !txtPass.getText().equals(txtRPass.getText())) {
            MostrarMensaje("Las Contraseñas no coinciden.", "Error");
            Correcto = false;
        }


        //Chequeo Nombre Vacio
        if (Correcto & txtNombre.getText().equals("")) {
            MostrarMensaje("Debe Ingresar un Nombre.", "Error");
            Correcto = false;
        }

        //Chequeo Apellido Vacio
        if (Correcto & txtApellido.getText().equals("")) {
            MostrarMensaje("Debe Ingresar un Apellido.", "Error");
            Correcto = false;
        }

        //Chequeo el Mail
        if (Correcto & !isEmail(txtMail.getText())) {
            MostrarMensaje("Es Incorrecto el E-Mail.", "Error");
            Correcto = false;
        }

        //Chequeo la Fecha
        if (Correcto & chsrDate.getDate() == null) {
            MostrarMensaje("Problemas en la Fecha.", "Error");
            Correcto = false;
        }

        if (Correcto & chsrDate.getDate().after(new Date())) {
            MostrarMensaje("Fecha Posterior a hoy.", "Error");
            Correcto = false;
        }

        String imagePath = "";
        if (imageFile != null) {
            imagePath = imageFile.getPath();
        }
        DataUsuario Nuevo = null;
        try {
            if (rdProve.isSelected()) {

                //Chequeo Comapnia Vacio
                if (Correcto & txtComp.getText().equals("")) {
                    MostrarMensaje("Debe Ingresar una Comañia.", "Error");
                    Correcto = false;
                }

                //Chequeo WEB Vacio
                if (Correcto & txtWeb.getText().equals("")) {
                    MostrarMensaje("Debe Ingresar un Sitio Web.", "Error");
                    Correcto = false;
                }

                Nuevo = new DataProveedor(txtNick.getText(), txtPass.getText(), txtMail.getText(), txtNombre.getText(), txtApellido.getText(), chsrDate.getDate());
                Nuevo.setImagen(imagePath);
                ((DataProveedor) Nuevo).setCompania(txtComp.getText());
                ((DataProveedor) Nuevo).setSitioWeb(txtWeb.getText());
            } else {
                Nuevo = new DataCliente(txtNick.getText(), txtPass.getText(), txtMail.getText(), txtNombre.getText(), txtApellido.getText(), chsrDate.getDate());
                Nuevo.setImagen(imagePath);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        //chequeo las exeptions 
        if (Correcto) {
            try {
                IAU.ingresarDataUsuario(Nuevo);
                IAU.altaUsuario();
            } catch (Exception e) {
                Correcto = false;
                MostrarMensaje(e.getMessage(), "Error");
            }
        }

        if (Correcto) {
            MostrarMensaje("El Usuario se registro correctamente.", "Correcto");
            doClose();
        }
    }//GEN-LAST:event_AddUsuActionPerformed

    private void chsrDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chsrDatePropertyChange
    }//GEN-LAST:event_chsrDatePropertyChange

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtRPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRPassActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUsu;
    private javax.swing.JLabel Etiqueta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSelect;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.toedter.calendar.JDateChooser chsrDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblSW;
    private javax.swing.JPanel paneProve;
    private javax.swing.JRadioButton rdClie;
    private javax.swing.JRadioButton rdProve;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtComp;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNick;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtRPass;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables
}
