package Presentacion;

import DataTypes.DataCliente;
import DataTypes.DataEstado;
import DataTypes.DataLinea;
import DataTypes.DataOrdenCompra;
import DataTypes.DataUsuario;
import Interfaces.Fabrica;
import Interfaces.IVerInfoCliente;
import Extras.UtilImage;
import java.awt.Dimension;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class VerInfoCliente extends javax.swing.JInternalFrame {

    private IVerInfoCliente IVC;
    private Map<String, DataCliente> Datas;
    private DataUsuario selec;
    private Map<Integer, DataOrdenCompra> doc;

    private void resetTabla(JTable Tabla) {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.setColumnIdentifiers(new Object[]{"NickName", "E-Mail"});
        for (Map.Entry<String, DataCliente> entry : Datas.entrySet()) {
            modelo.addRow(new Object[]{entry.getValue().getNickname(), entry.getValue().getMail()});
        }
        Tabla.setModel(modelo);

    }

    private void resetTablaOrdenes(JTable TablaO) {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            DefaultTableModel modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };
            modelo.setColumnIdentifiers(new Object[]{"Numero", "Modificada", "Costo Total(U$S)"});

            doc = IVC.listarOrdenesCliente();
            for (Map.Entry<Integer, DataOrdenCompra> entry : doc.entrySet()) {
                DataOrdenCompra dC = entry.getValue();
                Date F = dC.getEstado().getFecha();
                modelo.addRow(new Object[]{dC.getNumero(), sdf.format(F), dC.getTotal()});
            }
            TablaO.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void MostrarMensaje(String Mensaje, String Titulo) {
        JOptionPane.showMessageDialog(this,
                Mensaje,
                Titulo,
                JOptionPane.INFORMATION_MESSAGE);
    }

    public VerInfoCliente() {
        IVC = Fabrica.getIVC();
        Datas = IVC.listarClientes();

        initComponents();

        this.resetTabla(Tabla);

        //Maneja tamaño
        Presentacion MAIN = Presentacion.getPrincipal();
        Integer Alto = MAIN.getHeight() - 60;
        Integer Ancho = MAIN.getWidth() - 10;
        this.setPreferredSize(new Dimension(Ancho, Alto));
        paneDatos.setVisible(false);
        paneOrdenes.setVisible(false);
        paneLineas.setVisible(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonSalir = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        paneOrdenes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaOrdenes = new javax.swing.JTable();
        paneUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        paneLineas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaLineas = new javax.swing.JTable();
        txtE1 = new javax.swing.JTextField();
        txtE2 = new javax.swing.JTextField();
        txtE3 = new javax.swing.JTextField();
        lblE1 = new javax.swing.JLabel();
        lblE2 = new javax.swing.JLabel();
        lblE3 = new javax.swing.JLabel();
        paneDatos = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNick = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        Etiqueta = new javax.swing.JLabel();
        btnOrdenes = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setTitle("Ver Informacion del Cliente");
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setText("Ordenes de Compra");

        tablaOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaOrdenes.getTableHeader().setReorderingAllowed(false);
        tablaOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaOrdenesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaOrdenes);

        javax.swing.GroupLayout paneOrdenesLayout = new javax.swing.GroupLayout(paneOrdenes);
        paneOrdenes.setLayout(paneOrdenesLayout);
        paneOrdenesLayout.setHorizontalGroup(
            paneOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOrdenesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneOrdenesLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        paneOrdenesLayout.setVerticalGroup(
            paneOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOrdenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nick", "E-Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.getTableHeader().setReorderingAllowed(false);
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);
        Tabla.getColumnModel().getColumn(0).setResizable(false);
        Tabla.getColumnModel().getColumn(1).setResizable(false);

        javax.swing.GroupLayout paneUsuariosLayout = new javax.swing.GroupLayout(paneUsuarios);
        paneUsuarios.setLayout(paneUsuariosLayout);
        paneUsuariosLayout.setHorizontalGroup(
            paneUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneUsuariosLayout.setVerticalGroup(
            paneUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        tablaLineas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaLineas.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaLineas);

        txtE1.setText("jTextField1");

        txtE2.setText("jTextField2");

        txtE3.setText("jTextField3");

        lblE1.setText("Recibida");

        lblE2.setText("jLabel9");

        lblE3.setText("jLabel10");

        javax.swing.GroupLayout paneLineasLayout = new javax.swing.GroupLayout(paneLineas);
        paneLineas.setLayout(paneLineasLayout);
        paneLineasLayout.setHorizontalGroup(
            paneLineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLineasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneLineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLineasLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(paneLineasLayout.createSequentialGroup()
                        .addGroup(paneLineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblE1)
                            .addComponent(txtE1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneLineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtE2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblE2))
                        .addGap(18, 18, 18)
                        .addGroup(paneLineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneLineasLayout.createSequentialGroup()
                                .addComponent(lblE3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(paneLineasLayout.createSequentialGroup()
                                .addComponent(txtE3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );

        paneLineasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtE1, txtE2, txtE3});

        paneLineasLayout.setVerticalGroup(
            paneLineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLineasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(paneLineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblE2)
                    .addComponent(lblE3)
                    .addComponent(lblE1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneLineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtNombre.setEditable(false);
        txtNombre.setAutoscrolls(false);

        txtMail.setEditable(false);
        txtMail.setAutoscrolls(false);

        txtApellido.setEditable(false);
        txtApellido.setAutoscrolls(false);

        txtNick.setEditable(false);
        txtNick.setAutoscrolls(false);

        jLabel5.setText("Fecha de Nacimiento:");

        jLabel4.setText("E-Mail: ");

        jLabel3.setText("Nickname: ");

        jLabel2.setText("Apellido: ");

        jLabel1.setText("Nombre: ");

        txtFecha.setEditable(false);
        txtFecha.setAutoscrolls(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        Etiqueta.setText("...");

        btnOrdenes.setText("Mas Info.");
        btnOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneDatosLayout = new javax.swing.GroupLayout(paneDatos);
        paneDatos.setLayout(paneDatosLayout);
        paneDatosLayout.setHorizontalGroup(
            paneDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido)
                    .addComponent(txtFecha)
                    .addComponent(txtNick)
                    .addComponent(txtMail)
                    .addGroup(paneDatosLayout.createSequentialGroup()
                        .addGroup(paneDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(paneDatosLayout.createSequentialGroup()
                        .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnOrdenes)))
                .addContainerGap())
        );
        paneDatosLayout.setVerticalGroup(
            paneDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrdenes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneLineas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paneLineas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonSalir)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(paneDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paneUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        Presentacion.SwapMenu();
        this.setVisible(false);
        this.hide();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    }//GEN-LAST:event_formComponentShown

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
    }//GEN-LAST:event_formComponentMoved

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        try {
            paneOrdenes.setVisible(false);
            if (Tabla.getSelectedRow() != -1) {

                selec = Datas.get(Tabla.getValueAt(Tabla.getSelectedRow(), 0).toString());
                IVC.seleccionarCliente(selec.getNickname());

                txtNombre.setText(selec.getNombre());
                txtApellido.setText(selec.getApellido());
                Date F = selec.getFechaNac();

                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                txtFecha.setText(sdf.format(F));

                txtNick.setText(selec.getNickname());
                txtMail.setText(selec.getMail());

                Etiqueta.setText("");
                if (selec.getBimagen() == null) {
                    Etiqueta.setIcon(null);
                } else {
                    Etiqueta.setIcon(Presentacion.fixImagen(UtilImage.toBufferedImage(selec.getBimagen()), Etiqueta));
                }
                repaint();
                paneDatos.setVisible(true);
            } else {
                paneDatos.setVisible(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenesActionPerformed
        boolean Flag = paneUsuarios.isVisible();
        if (Flag) {
            paneUsuarios.setVisible(false);
            resetTablaOrdenes(tablaOrdenes);
            paneOrdenes.setVisible(true);
            btnOrdenes.setText("Menos Info.");
        } else {
            paneLineas.setVisible(false);
            paneUsuarios.setVisible(true);
            paneOrdenes.setVisible(false);
            btnOrdenes.setText("Mas Info.");
        }


    }//GEN-LAST:event_btnOrdenesActionPerformed

    private void tablaOrdenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaOrdenesMouseClicked

        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        DataOrdenCompra sel = doc.get((Integer) tablaOrdenes.getValueAt(tablaOrdenes.getSelectedRow(), 0));

        List<DataLinea> Lines;
        Lines = sel.getLineas();

        modelo.setColumnIdentifiers(new Object[]{"Nombre producto", "Cantidad", "Precio unitario", "Subtotal"});
        for (Iterator it = Lines.iterator(); it.hasNext();) {
            DataLinea dl = (DataLinea) it.next();
            modelo.addRow(new Object[]{dl.getProd().getNombre(), dl.getCantidad(), dl.getPrecioProd(), dl.getPrecioLinea()});
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        List<DataEstado> DEs = sel.getEstados();
        lblE1.setVisible(false);
        lblE2.setVisible(false);
        lblE3.setVisible(false);
        txtE1.setVisible(false);
        txtE2.setVisible(false);
        txtE3.setVisible(false);
        if (DEs.size() >= 1) {
            lblE1.setText(DEs.get(0).getEst().name());
            txtE1.setText(sdf.format(DEs.get(0).getFecha()));
            lblE1.setVisible(true);
            txtE1.setVisible(true);
        }
        if (DEs.size() >= 2) {
            lblE2.setText(DEs.get(1).getEst().name());
            txtE2.setText(sdf.format(DEs.get(1).getFecha()));
            lblE2.setVisible(true);
            txtE2.setVisible(true);
        }
        if (DEs.size() >= 3) {
            lblE3.setText(DEs.get(2).getEst().name());
            txtE3.setText(sdf.format(DEs.get(2).getFecha()));
            lblE3.setVisible(true);
            txtE3.setVisible(true);
        }

        tablaLineas.setModel(modelo);
        paneLineas.setVisible(true);



    }//GEN-LAST:event_tablaOrdenesMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonSalir;
    private javax.swing.JLabel Etiqueta;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnOrdenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblE1;
    private javax.swing.JLabel lblE2;
    private javax.swing.JLabel lblE3;
    private javax.swing.JPanel paneDatos;
    private javax.swing.JPanel paneLineas;
    private javax.swing.JPanel paneOrdenes;
    private javax.swing.JPanel paneUsuarios;
    private javax.swing.JTable tablaLineas;
    private javax.swing.JTable tablaOrdenes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtE1;
    private javax.swing.JTextField txtE2;
    private javax.swing.JTextField txtE3;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNick;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
