package Presentacion;

import DataTypes.DataCategoria;
import DataTypes.DataProducto;
import Interfaces.Fabrica;
import Interfaces.IVerModProducto;
import Extras.UtilImage;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

public class VerProd extends javax.swing.JInternalFrame {

    int IteradorImg;
    DataProducto SelProd;
    Map<Integer, DataProducto> Productos;
    IVerModProducto IVMP = Fabrica.getIVMP();
    int[] NRefs;
    String[] Lista;

    /**
     * Creates new form DelProd
     */
    public VerProd() {
        IteradorImg = 0;
        initComponents();
        //Maneja tamaño
        Presentacion MAIN = Presentacion.getPrincipal();
        Integer Alto = MAIN.getHeight() - 60;
        Integer Ancho = MAIN.getWidth() - 10;
        this.setPreferredSize(new Dimension(Ancho, Alto));
        //Visible
        this.setVisible(true);

        String[] texto = {"Seleccione un Producto"};

        listProductos.setModel(new DefaultComboBoxModel(texto));

        Presentacion.getPrincipal().cargarArbol(Arbol);

        lblImg.setVisible(false);
        Panel.setVisible(false);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Arbol = new javax.swing.JTree();
        listProductos = new javax.swing.JComboBox();
        Panel = new javax.swing.JPanel();
        txtNRef = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEsp = new javax.swing.JTextArea();
        txtProve = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        listCate = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblImg = new javax.swing.JLabel();

        setTitle("Ver Informacion Producto");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        Arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArbolMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Arbol);

        listProductos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "eaaa 1", "Item 2", "Item 3", "Item 4" }));
        listProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listProductosActionPerformed(evt);
            }
        });

        Panel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelComponentShown(evt);
            }
        });

        txtNRef.setText("jTextField1");
        txtNRef.setAutoscrolls(false);
        txtNRef.setEnabled(false);
        txtNRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNRefActionPerformed(evt);
            }
        });

        jLabel1.setText("Nº de Referencia");

        txtEsp.setColumns(20);
        txtEsp.setRows(5);
        txtEsp.setAutoscrolls(false);
        txtEsp.setEnabled(false);
        jScrollPane1.setViewportView(txtEsp);

        txtProve.setText("jTextField2");
        txtProve.setAutoscrolls(false);
        txtProve.setEnabled(false);
        txtProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveActionPerformed(evt);
            }
        });

        txtDesc.setText("jTextField3");
        txtDesc.setAutoscrolls(false);
        txtDesc.setEnabled(false);

        listCate.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Categoria" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listCate.setAutoscrolls(false);
        listCate.setEnabled(false);
        jScrollPane4.setViewportView(listCate);

        jLabel2.setText("Proveedor");

        jLabel3.setText("Categorias");

        jLabel4.setText("Descripcion");

        jLabel5.setText("Especificacion");

        jLabel6.setText("Precio (U$S)");

        txtPrecio.setText("jTextField1");
        txtPrecio.setAutoscrolls(false);
        txtPrecio.setEnabled(false);

        lblImg.setText("...");
        lblImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDesc)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel5)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNRef, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtProve, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(txtNRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listProductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(90, 90, 90)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnSalir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 178, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        this.hide();
        Presentacion.SwapMenu();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void PanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelComponentShown
    }//GEN-LAST:event_PanelComponentShown

    private void txtNRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNRefActionPerformed

    private void txtProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveActionPerformed

    private void ArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArbolMouseClicked
        try {
            Panel.setVisible(false);

            String[] texto = {"Seleccione un Producto"};

            listProductos.setModel(new DefaultComboBoxModel(texto));

            if (Arbol.getLeadSelectionPath() != null) {
                String seleccion = Arbol.getLeadSelectionPath().getLastPathComponent().toString();
                if (IVMP.seleccionarCategoria(seleccion).getEsSimple()) {

                    Productos = IVMP.listarProductosCategoria();
                    Lista = new String[Productos.size() + 1];
                    NRefs = new int[Productos.size()];

                    int i = 0;
                    for (Map.Entry<Integer, DataProducto> entry : Productos.entrySet()) {
                        Lista[i] = entry.getValue().getNombre();
                        NRefs[i] = entry.getValue().getNRef();
                        i++;
                    }
                    Lista[i] = "Seleccione un Producto";

                    DefaultComboBoxModel Modelo = new DefaultComboBoxModel(Lista);
                    listProductos.setModel(Modelo);
                    listProductos.setSelectedIndex(i);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ArbolMouseClicked

    private void listProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listProductosActionPerformed
        try {
            if (!listProductos.getSelectedItem().toString().equals("Seleccione un Producto")) {
                SelProd = Productos.get(NRefs[listProductos.getSelectedIndex()]);

                txtProve.setText(SelProd.getProveedor());
                txtNRef.setText(SelProd.getNRef().toString());
                txtDesc.setText(SelProd.getDescripcion());
                txtPrecio.setText(SelProd.getPrecio().toString());
                txtEsp.setText(SelProd.getEspecificacion());

                IVMP.seleccionarProducto(NRefs[listProductos.getSelectedIndex()]);

                Map<String, DataCategoria> Cates = IVMP.listarCategoriaProductos();

                DefaultListModel LModel = new DefaultListModel();
                for (Map.Entry<String, DataCategoria> entry : Cates.entrySet()) {
                    LModel.addElement(entry.getValue().getNombre());
                }
                listCate.setModel(LModel);


                lblImg.setVisible(true);
                lblImg.setText("");
                if (SelProd.getImgs(0) == null) {
                    lblImg.setIcon(null);
                } else {
                    lblImg.setIcon(Presentacion.fixImagen(UtilImage.toBufferedImage(SelProd.getImgs(0)), lblImg));
                }
                repaint();

                Panel.setVisible(true);
            }
        } catch (Exception e) {
            //e.printStackTrace();
        }
    }//GEN-LAST:event_listProductosActionPerformed

    private void lblImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgMouseClicked
        try {
            IteradorImg = (IteradorImg + 1) % 3;
            if (SelProd.getImgs(IteradorImg) == null) {
                IteradorImg = 0;
            }

            lblImg.setText("");
            if (SelProd.getImgs(IteradorImg) == null) {
                lblImg.setIcon(null);
            } else {
                lblImg.setIcon(Presentacion.fixImagen(UtilImage.toBufferedImage(SelProd.getImgs(IteradorImg)), lblImg));
            }
            repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblImgMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Arbol;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblImg;
    private javax.swing.JList listCate;
    private javax.swing.JComboBox listProductos;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextArea txtEsp;
    private javax.swing.JTextField txtNRef;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProve;
    // End of variables declaration//GEN-END:variables
}
