
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Jun 16 14:25:19 UYT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 35;
  public static final int PUNTOYCOMA = 37;
  public static final int INTEGER = 25;
  public static final int BETWEEN = 20;
  public static final int UPDATE = 13;
  public static final int ASTERISCO = 30;
  public static final int DATE = 26;
  public static final int DELETE = 16;
  public static final int WHERE = 10;
  public static final int CURIZQ = 39;
  public static final int NOT = 18;
  public static final int MENORIGUAL = 33;
  public static final int IS = 21;
  public static final int AND = 19;
  public static final int IGUAL = 36;
  public static final int OR = 22;
  public static final int ON = 4;
  public static final int VARCHAR = 24;
  public static final int SELECT = 8;
  public static final int ID = 41;
  public static final int MAYORIGUAL = 34;
  public static final int EOF = 0;
  public static final int TABLE = 5;
  public static final int error = 1;
  public static final int COMA = 38;
  public static final int VALUES = 17;
  public static final int MENOS = 28;
  public static final int NULL = 23;
  public static final int EXISTS = 15;
  public static final int MENOR = 31;
  public static final int NUMBER = 43;
  public static final int FROM = 9;
  public static final int MAYOR = 32;
  public static final int BARRA = 29;
  public static final int INTO = 12;
  public static final int CURDER = 40;
  public static final int INDEX = 3;
  public static final int INSERT = 11;
  public static final int CREATE = 2;
  public static final int DROP = 7;
  public static final int STRING = 42;
  public static final int AS = 6;
  public static final int SET = 14;
  public static final int MAS = 27;
}

