/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import conexion.CSesion;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import static presentacion.Principal.setPanel;

/**
 *
 * @author tprog077
 */
public class Chat extends javax.swing.JPanel {

    private static String nProv = "";
    private CSesion cs = null;
    private Timer timer = new Timer();

    public static void setnProv(String nProv) {
        Chat.nProv = nProv;
    }

    private void PreguntarMens() {
        TimerTask timerTask = new TimerTask() {
            @Override
            public void run() {
                try {
                    if (cs.tengoMsj()) {
                        cargarLista(listCqa);
                        cargarBloque(txtAreaChat);
                    }
                } catch (Exception ex) {
                }
            }
        };
        if (timer != null) {
            timer = new Timer();
        }
        timer.scheduleAtFixedRate(timerTask, 0, 1000);
    }

    private void cargarLista(JComboBox Lista) throws Exception {
        List cqa = cs.conQuienHable();
        DefaultComboBoxModel LModel = new DefaultComboBoxModel();
        for (Object nom : cqa) {
            LModel.addElement((String) nom);
        }
        Lista.setModel(LModel);
    }

    private void cargarBloque(JTextArea Bloque) throws Exception {
        List cqa = cs.conversacionCon(nProv);
        String Text = "";
        for (Object msj : cqa) {
            Text = ((String) msj) + "\n" + Text;
        }
        Bloque.setText(Text);
    }

    /**
     * Creates new form Chat
     */
    public Chat() throws Exception {
        initComponents();
        this.cs = CSesion.getInstance();
        cargarLista(listCqa);

        if (nProv.equals("")) {
            nProv = listCqa.getItemAt(0).toString();
            cargarBloque(txtAreaChat);
            lblChatCon.setText("Chat con " + nProv);
        } else {
            lblChatCon.setText("Chat con " + nProv);
        }

        PreguntarMens();
        cargarBloque(txtAreaChat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listCqa = new javax.swing.JComboBox();
        txtChat = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        lblChatCon = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaChat = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));

        listCqa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listCqa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCqaActionPerformed(evt);
            }
        });

        txtChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChatActionPerformed(evt);
            }
        });

        btnEnviar.setText(">");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblChatCon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblChatCon.setText("jLabel1");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtAreaChat.setEditable(false);
        txtAreaChat.setColumns(20);
        txtAreaChat.setRows(5);
        txtAreaChat.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtAreaChat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChatCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listCqa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChatCon)
                    .addComponent(listCqa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChatActionPerformed

    private void listCqaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCqaActionPerformed
        try {
            nProv = listCqa.getSelectedItem().toString();
            cargarBloque(txtAreaChat);
            lblChatCon.setText("Chat con " + nProv);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_listCqaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        setPanel(new InfoPerfil());
        timer.cancel();
        timer = null;
        hide();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:

        String quienSoy = cs.verInfoPerfil().getNickname();
        try {
            cs.mandarMensaje(nProv, txtChat.getText());
        } catch (Exception e) {
        }
        //txtAreaChat.append(quienSoy + txtChat.getText() + "\n");
        txtChat.setText("");
    }//GEN-LAST:event_btnEnviarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChatCon;
    private javax.swing.JComboBox listCqa;
    private javax.swing.JTextArea txtAreaChat;
    private javax.swing.JTextField txtChat;
    // End of variables declaration//GEN-END:variables
}
