/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import conexion.CSesion;
import persistencia.PUsuario;
import extras.utilDate;
import extras.utilImage;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static presentacion.Principal.setPanel;
import publisher.DataCliente;
import publisher.DataUsuario;

/**
 *
 * @author Faller
 */
public class InfoPerfil extends Principal.MyPanel {

    private void salir() throws Exception {
        CSesion.getInstance().cerrarSesion();
        PUsuario.dispose();
        Principal.setConexion(null);
        Principal.setPanel(new InicioSesion());
        hide();
    }

    public InfoPerfil() {
        Principal.getPrincipal().super();

        initComponents();
        lblPic.setIcon(new ImageIcon("src/imagenes/icon.png"));

        DataUsuario du = CSesion.getInstance().verInfoPerfil();
        lblNom.setText(du.getNombre() + " " + du.getApellido());
        txtNick.setText(du.getNickname());
        txtFna.setText(utilDate.formatS(du.getFechaNac()));
        if (du instanceof DataCliente) {
            txtTUsu.setText("Cliente");
            btnReclamos.setVisible(false);
        } else {
            btnOrd.setVisible(false);
            btnReclamar.setVisible(false);
            txtTUsu.setText("Proveedor");
        }
        if (du.getBimagen() != null) {
            try {
                BufferedImage BI = utilImage.toBufferedImage(du.getBimagen());
                ImageIcon II = utilImage.fixImagen(BI, 100, 100);
                lblPic.setIcon(II);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblPic = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        txtFna = new javax.swing.JTextField();
        txtTUsu = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        btnOrd = new javax.swing.JButton();
        btnReclamos = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnReclamar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));
        setPreferredSize(new java.awt.Dimension(320, 480));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        lblPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPic.setText("foto");

        lblNom.setFont(new java.awt.Font("Forte", 0, 28)); // NOI18N
        lblNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNom.setText("Ricky Ricón");
        lblNom.setToolTipText("");

        jLabel3.setText("Nickname:");

        jLabel4.setText("Fecha de Nacimiento:");

        jLabel5.setText("Tipo Usuario: ");

        txtNick.setEditable(false);
        txtNick.setBackground(new java.awt.Color(255, 255, 255));
        txtNick.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        txtNick.setText("jTextField1");
        txtNick.setAutoscrolls(false);
        txtNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNickActionPerformed(evt);
            }
        });

        txtFna.setEditable(false);
        txtFna.setBackground(new java.awt.Color(255, 255, 255));
        txtFna.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        txtFna.setText("jTextField2");
        txtFna.setAutoscrolls(false);

        txtTUsu.setEditable(false);
        txtTUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtTUsu.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        txtTUsu.setText("jTextField3");
        txtTUsu.setAutoscrolls(false);

        btnLogout.setText("Cerrar Sesion");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnOrd.setText("Ver ordenes");
        btnOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdActionPerformed(evt);
            }
        });

        btnReclamos.setText("Ver Reclamos");
        btnReclamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReclamosMouseClicked(evt);
            }
        });
        btnReclamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReclamosActionPerformed(evt);
            }
        });

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnReclamar.setText("Reclamar");
        btnReclamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReclamarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReclamos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLogout))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtTUsu))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFna, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReclamar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNom, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnOrd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReclamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReclamar)
                .addGap(29, 29, 29)
                .addComponent(btnLogout)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNickActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int n = JOptionPane.showConfirmDialog(
                this,
                "Cerrando Sesion\n¿Realmente quiere desea salir?",
                "Saliendo...",
                JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {
            try {
                salir();
            } catch (Exception e) {
                Principal.MostrarMensaje(e.getMessage(), "Fallo");
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdActionPerformed
        try {

            setPanel(new VerOrden());
            hide();
        } catch (Exception ex) {
            Principal.MostrarMensaje(ex.getMessage(), "Fallo");
        }
    }//GEN-LAST:event_btnOrdActionPerformed

    private void btnReclamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReclamosMouseClicked
        try {
            setPanel(new ListReclamos());
            hide();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnReclamosMouseClicked

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        setPanel(new ListCates()); // lista categorias
        hide();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnReclamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReclamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReclamosActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_formMouseDragged

    private void btnReclamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReclamarActionPerformed
        // TODO add your handling code here:
        try {
            setPanel(new ListProdRec());
            hide();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnReclamarActionPerformed
// <editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrd;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReclamar;
    private javax.swing.JButton btnReclamos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPic;
    private javax.swing.JTextField txtFna;
    private javax.swing.JTextField txtNick;
    private javax.swing.JTextField txtTUsu;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
