/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import conexion.Conexion;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import publisher.DataOrdenCompra;
import static extras.utilDate.formatS;
import java.util.Date;

/**
 *
 * @author tprog080
 */
public class VerOrden extends javax.swing.JPanel {

    private dataType.DataOrdenCompra selec;
    private List<dataType.DataOrdenCompra> Datas;

    public VerOrden() throws Exception {
        initComponents();

        Conexion con = new Conexion();
        Datas = con.getOrdenes();
        try {
            resetTablaOrdenes(Tablilla);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }


        setVisible(true);
    }

    private void resetTablaOrdenes(JTable TablaO) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.setColumnIdentifiers(new Object[]{"Numero", "Fecha", "Costo Total(U$S)"});
        for (dataType.DataOrdenCompra doc : Datas) {
            List<dataType.DataEstado> LdE = doc.getEstados();
            Date F = LdE.get(LdE.size() - 1).getFecha();
            modelo.addRow(new Object[]{doc.getnOrd(), formatS(F), doc.getTotal()});
        }

        TablaO.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablilla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Orden de Compra");

        Tablilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tablilla.setFillsViewportHeight(true);
        Tablilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablilla);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablillaMouseClicked
        try {
            Integer num = Integer.parseInt(Tablilla.getValueAt(Tablilla.getSelectedRow(), 0).toString());
            for (dataType.DataOrdenCompra dc : Datas) {

                if (num == dc.getnOrd()) {
                    selec = dc;
                }
            }

            Principal.setPanel(new VerLineas(selec));
            hide();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_TablillaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Principal.setPanel(new InfoPerfil());
        hide();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablilla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
