
package publisher;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PBuscarCategoriaService", targetNamespace = "http://Publisher/", wsdlLocation = "http://localhost:20016/PBC?wsdl")
public class PBuscarCategoriaService
    extends Service
{

    private final static URL PBUSCARCATEGORIASERVICE_WSDL_LOCATION;
    private final static WebServiceException PBUSCARCATEGORIASERVICE_EXCEPTION;
    private final static QName PBUSCARCATEGORIASERVICE_QNAME = new QName("http://Publisher/", "PBuscarCategoriaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20016/PBC?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PBUSCARCATEGORIASERVICE_WSDL_LOCATION = url;
        PBUSCARCATEGORIASERVICE_EXCEPTION = e;
    }

    public PBuscarCategoriaService() {
        super(__getWsdlLocation(), PBUSCARCATEGORIASERVICE_QNAME);
    }

    public PBuscarCategoriaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PBUSCARCATEGORIASERVICE_QNAME, features);
    }

    public PBuscarCategoriaService(URL wsdlLocation) {
        super(wsdlLocation, PBUSCARCATEGORIASERVICE_QNAME);
    }

    public PBuscarCategoriaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PBUSCARCATEGORIASERVICE_QNAME, features);
    }

    public PBuscarCategoriaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PBuscarCategoriaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PBuscarCategoria
     */
    @WebEndpoint(name = "PBuscarCategoriaPort")
    public PBuscarCategoria getPBuscarCategoriaPort() {
        return super.getPort(new QName("http://Publisher/", "PBuscarCategoriaPort"), PBuscarCategoria.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PBuscarCategoria
     */
    @WebEndpoint(name = "PBuscarCategoriaPort")
    public PBuscarCategoria getPBuscarCategoriaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publisher/", "PBuscarCategoriaPort"), PBuscarCategoria.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PBUSCARCATEGORIASERVICE_EXCEPTION!= null) {
            throw PBUSCARCATEGORIASERVICE_EXCEPTION;
        }
        return PBUSCARCATEGORIASERVICE_WSDL_LOCATION;
    }

}
