
package publisher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PConfirmarOrden", targetNamespace = "http://Publisher/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PConfirmarOrden {


    /**
     * 
     * @param num
     * @param numeroSesion
     * @return
     *     returns publisher.DataOrdenCompra
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PConfirmarOrden/seleccionarOrdenRequest", output = "http://Publisher/PConfirmarOrden/seleccionarOrdenResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PConfirmarOrden/seleccionarOrden/Fault/Exception")
    })
    public DataOrdenCompra seleccionarOrden(
        @WebParam(name = "num", partName = "num")
        int num,
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nick
     * @param numeroSesion
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Publisher/PConfirmarOrden/confirmarOrdenRequest", output = "http://Publisher/PConfirmarOrden/confirmarOrdenResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PConfirmarOrden/confirmarOrden/Fault/Exception")
    })
    public void confirmarOrden(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PConfirmarOrden/reservarSesionRequest", output = "http://Publisher/PConfirmarOrden/reservarSesionResponse")
    public int reservarSesion();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Publisher/PConfirmarOrden/stopRequest", output = "http://Publisher/PConfirmarOrden/stopResponse")
    public void stop();

}
