
package publisher;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PInicioSesionService", targetNamespace = "http://Publisher/", wsdlLocation = "http://localhost:20016/PIS?wsdl")
public class PInicioSesionService
    extends Service
{

    private final static URL PINICIOSESIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PINICIOSESIONSERVICE_EXCEPTION;
    private final static QName PINICIOSESIONSERVICE_QNAME = new QName("http://Publisher/", "PInicioSesionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20016/PIS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PINICIOSESIONSERVICE_WSDL_LOCATION = url;
        PINICIOSESIONSERVICE_EXCEPTION = e;
    }

    public PInicioSesionService() {
        super(__getWsdlLocation(), PINICIOSESIONSERVICE_QNAME);
    }

    public PInicioSesionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PINICIOSESIONSERVICE_QNAME, features);
    }

    public PInicioSesionService(URL wsdlLocation) {
        super(wsdlLocation, PINICIOSESIONSERVICE_QNAME);
    }

    public PInicioSesionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PINICIOSESIONSERVICE_QNAME, features);
    }

    public PInicioSesionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PInicioSesionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PInicioSesion
     */
    @WebEndpoint(name = "PInicioSesionPort")
    public PInicioSesion getPInicioSesionPort() {
        return super.getPort(new QName("http://Publisher/", "PInicioSesionPort"), PInicioSesion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PInicioSesion
     */
    @WebEndpoint(name = "PInicioSesionPort")
    public PInicioSesion getPInicioSesionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publisher/", "PInicioSesionPort"), PInicioSesion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PINICIOSESIONSERVICE_EXCEPTION!= null) {
            throw PINICIOSESIONSERVICE_EXCEPTION;
        }
        return PINICIOSESIONSERVICE_WSDL_LOCATION;
    }

}
