
package publisher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PInicioSesion", targetNamespace = "http://Publisher/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PInicioSesion {


    /**
     * 
     * @param num
     * @param nickName
     * @param cant
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Publisher/PInicioSesion/agregaLineaRequest", output = "http://Publisher/PInicioSesion/agregaLineaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/agregaLinea/Fault/Exception")
    })
    public void agregaLinea(
        @WebParam(name = "cant", partName = "cant")
        int cant,
        @WebParam(name = "num", partName = "num")
        int num,
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nickName
     * @return
     *     returns publisher.DataOrdenCompra
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PInicioSesion/verCarritoRequest", output = "http://Publisher/PInicioSesion/verCarritoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/verCarrito/Fault/Exception")
    })
    public DataOrdenCompra verCarrito(
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nickName
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Publisher/PInicioSesion/generarOrdenRequest", output = "http://Publisher/PInicioSesion/generarOrdenResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/generarOrden/Fault/Exception")
    })
    public void generarOrden(
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nRef
     * @param nickName
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PInicioSesion/puedeComentarRequest", output = "http://Publisher/PInicioSesion/puedeComentarResponse")
    public boolean puedeComentar(
        @WebParam(name = "nRef", partName = "nRef")
        int nRef,
        @WebParam(name = "NickName", partName = "NickName")
        String nickName);

    /**
     * 
     * @param contra
     * @param nm
     * @return
     *     returns publisher.DataUsuario
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PInicioSesion/inicioSesionRequest", output = "http://Publisher/PInicioSesion/inicioSesionResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/inicioSesion/Fault/Exception")
    })
    public DataUsuario inicioSesion(
        @WebParam(name = "nm", partName = "nm")
        String nm,
        @WebParam(name = "contra", partName = "contra")
        String contra)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nickName
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Publisher/PInicioSesion/cerrarSesionRequest", output = "http://Publisher/PInicioSesion/cerrarSesionResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/cerrarSesion/Fault/Exception")
    })
    public void cerrarSesion(
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nickName
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Publisher/PInicioSesion/estoyOnlineRequest", output = "http://Publisher/PInicioSesion/estoyOnlineResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/estoyOnline/Fault/Exception")
    })
    public void estoyOnline(
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nickName
     * @return
     *     returns publisher.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PInicioSesion/verInfoPerfilRequest", output = "http://Publisher/PInicioSesion/verInfoPerfilResponse")
    public DataUsuario verInfoPerfil(
        @WebParam(name = "NickName", partName = "NickName")
        String nickName);

    /**
     * 
     * @param nRef
     * @param nickName
     * @param comen
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Publisher/PInicioSesion/comentarRequest", output = "http://Publisher/PInicioSesion/comentarResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/comentar/Fault/Exception")
    })
    public void comentar(
        @WebParam(name = "nRef", partName = "nRef")
        int nRef,
        @WebParam(name = "Comen", partName = "Comen")
        String comen,
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nRef
     * @param nickName
     * @param comen
     * @param padre
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Publisher/PInicioSesion/responderRequest", output = "http://Publisher/PInicioSesion/responderResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/responder/Fault/Exception")
    })
    public void responder(
        @WebParam(name = "nRef", partName = "nRef")
        int nRef,
        @WebParam(name = "Comen", partName = "Comen")
        String comen,
        @WebParam(name = "Padre", partName = "Padre")
        int padre,
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nickName
     * @param receptor
     * @param mensaje
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Publisher/PInicioSesion/mandarMensajeRequest", output = "http://Publisher/PInicioSesion/mandarMensajeResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/mandarMensaje/Fault/Exception")
    })
    public void mandarMensaje(
        @WebParam(name = "Receptor", partName = "Receptor")
        String receptor,
        @WebParam(name = "Mensaje", partName = "Mensaje")
        String mensaje,
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param otro
     * @param nickName
     * @return
     *     returns publisher.Coleccion
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PInicioSesion/conversacionConRequest", output = "http://Publisher/PInicioSesion/conversacionConResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/conversacionCon/Fault/Exception")
    })
    public Coleccion conversacionCon(
        @WebParam(name = "Otro", partName = "Otro")
        String otro,
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param otro
     * @param nickName
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PInicioSesion/contarMensajesRequest", output = "http://Publisher/PInicioSesion/contarMensajesResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/contarMensajes/Fault/Exception")
    })
    public int contarMensajes(
        @WebParam(name = "Otro", partName = "Otro")
        String otro,
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nickName
     * @return
     *     returns publisher.Coleccion
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PInicioSesion/conQuienHableRequest", output = "http://Publisher/PInicioSesion/conQuienHableResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/conQuienHable/Fault/Exception")
    })
    public Coleccion conQuienHable(
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nickName
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PInicioSesion/tengoMsjRequest", output = "http://Publisher/PInicioSesion/tengoMsjResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PInicioSesion/tengoMsj/Fault/Exception")
    })
    public boolean tengoMsj(
        @WebParam(name = "NickName", partName = "NickName")
        String nickName)
        throws Exception_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Publisher/PInicioSesion/stopRequest", output = "http://Publisher/PInicioSesion/stopResponse")
    public void stop();

}
