
package publisher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PPuntaje", targetNamespace = "http://Publisher/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PPuntaje {


    /**
     * 
     * @param numeroSesion
     * @param nref
     */
    @WebMethod
    @Action(input = "http://Publisher/PPuntaje/seleccionarProductoRequest", output = "http://Publisher/PPuntaje/seleccionarProductoResponse")
    public void seleccionarProducto(
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion,
        @WebParam(name = "nref", partName = "nref")
        int nref);

    /**
     * 
     * @param nick
     * @param numeroSesion
     * @return
     *     returns publisher.DataCliente
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PPuntaje/seleccionarClienteRequest", output = "http://Publisher/PPuntaje/seleccionarClienteResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PPuntaje/seleccionarCliente/Fault/Exception")
    })
    public DataCliente seleccionarCliente(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion)
        throws Exception_Exception
    ;

    /**
     * 
     * @param numeroSesion
     * @return
     *     returns publisher.Coleccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PPuntaje/listarProductosCompradosRequest", output = "http://Publisher/PPuntaje/listarProductosCompradosResponse")
    public Coleccion listarProductosComprados(
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion);

    /**
     * 
     * @param numeroSesion
     * @param puntaje
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Publisher/PPuntaje/puntuarProductoRequest", output = "http://Publisher/PPuntaje/puntuarProductoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PPuntaje/puntuarProducto/Fault/Exception")
    })
    public void puntuarProducto(
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion,
        @WebParam(name = "puntaje", partName = "puntaje")
        int puntaje)
        throws Exception_Exception
    ;

    /**
     * 
     * @param numeroSesion
     * @return
     *     returns publisher.Coleccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PPuntaje/noPuntuadosRequest", output = "http://Publisher/PPuntaje/noPuntuadosResponse")
    public Coleccion noPuntuados(
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PPuntaje/reservarSesionRequest", output = "http://Publisher/PPuntaje/reservarSesionResponse")
    public int reservarSesion();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Publisher/PPuntaje/stopRequest", output = "http://Publisher/PPuntaje/stopResponse")
    public void stop();

}
