
package publisher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PReclamo", targetNamespace = "http://Publisher/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PReclamo {


    /**
     * 
     * @param nRef
     * @param numeroSesion
     * @return
     *     returns publisher.DataProducto
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PReclamo/seleccionarProductoRequest", output = "http://Publisher/PReclamo/seleccionarProductoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PReclamo/seleccionarProducto/Fault/Exception")
    })
    public DataProducto seleccionarProducto(
        @WebParam(name = "NRef", partName = "NRef")
        int nRef,
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nick
     * @param numeroSesion
     * @return
     *     returns publisher.DataCliente
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PReclamo/seleccionarClienteRequest", output = "http://Publisher/PReclamo/seleccionarClienteResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PReclamo/seleccionarCliente/Fault/Exception")
    })
    public DataCliente seleccionarCliente(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nick
     * @param numeroSesion
     * @return
     *     returns publisher.DataProveedor
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PReclamo/seleccionarProveedorRequest", output = "http://Publisher/PReclamo/seleccionarProveedorResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PReclamo/seleccionarProveedor/Fault/Exception")
    })
    public DataProveedor seleccionarProveedor(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion)
        throws Exception_Exception
    ;

    /**
     * 
     * @param numeroSesion
     * @return
     *     returns publisher.Coleccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PReclamo/listarReclamosRequest", output = "http://Publisher/PReclamo/listarReclamosResponse")
    public Coleccion listarReclamos(
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion);

    /**
     * 
     * @param texto
     * @param numeroSesion
     * @param nRec
     * @param prod
     */
    @WebMethod
    @Action(input = "http://Publisher/PReclamo/respRecRequest", output = "http://Publisher/PReclamo/respRecResponse")
    public void respRec(
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion,
        @WebParam(name = "texto", partName = "texto")
        String texto,
        @WebParam(name = "NRec", partName = "NRec")
        int nRec,
        @WebParam(name = "Prod", partName = "Prod")
        int prod);

    /**
     * 
     * @param texto
     * @param numeroSesion
     */
    @WebMethod
    @Action(input = "http://Publisher/PReclamo/altaReclamoRequest", output = "http://Publisher/PReclamo/altaReclamoResponse")
    public void altaReclamo(
        @WebParam(name = "texto", partName = "texto")
        String texto,
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PReclamo/reservarSesionRequest", output = "http://Publisher/PReclamo/reservarSesionResponse")
    public int reservarSesion();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Publisher/PReclamo/stopRequest", output = "http://Publisher/PReclamo/stopResponse")
    public void stop();

}
