
package publisher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PVerProducto", targetNamespace = "http://Publisher/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PVerProducto {


    /**
     * 
     * @return
     *     returns publisher.DataCategoria
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerProducto/listarCategoriasRequest", output = "http://Publisher/PVerProducto/listarCategoriasResponse")
    public DataCategoria listarCategorias();

    /**
     * 
     * @param nRef
     * @param numeroInstancia
     * @return
     *     returns publisher.DataProducto
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerProducto/seleccionarProductoRequest", output = "http://Publisher/PVerProducto/seleccionarProductoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PVerProducto/seleccionarProducto/Fault/Exception")
    })
    public DataProducto seleccionarProducto(
        @WebParam(name = "NRef", partName = "NRef")
        int nRef,
        @WebParam(name = "NumeroInstancia", partName = "NumeroInstancia")
        int numeroInstancia)
        throws Exception_Exception
    ;

    /**
     * 
     * @param numeroInstancia
     * @return
     *     returns publisher.Coleccion
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerProducto/listarCategoriaProductosRequest", output = "http://Publisher/PVerProducto/listarCategoriaProductosResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PVerProducto/listarCategoriaProductos/Fault/Exception")
    })
    public Coleccion listarCategoriaProductos(
        @WebParam(name = "NumeroInstancia", partName = "NumeroInstancia")
        int numeroInstancia)
        throws Exception_Exception
    ;

    /**
     * 
     * @param numeroInstancia
     * @param nCat
     * @return
     *     returns publisher.DataCategoria
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerProducto/seleccionarCategoriaRequest", output = "http://Publisher/PVerProducto/seleccionarCategoriaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PVerProducto/seleccionarCategoria/Fault/Exception")
    })
    public DataCategoria seleccionarCategoria(
        @WebParam(name = "nCat", partName = "nCat")
        String nCat,
        @WebParam(name = "NumeroInstancia", partName = "NumeroInstancia")
        int numeroInstancia)
        throws Exception_Exception
    ;

    /**
     * 
     * @param numeroInstancia
     * @return
     *     returns publisher.Coleccion
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerProducto/listarProductosCategoriaRequest", output = "http://Publisher/PVerProducto/listarProductosCategoriaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PVerProducto/listarProductosCategoria/Fault/Exception")
    })
    public Coleccion listarProductosCategoria(
        @WebParam(name = "NumeroInstancia", partName = "NumeroInstancia")
        int numeroInstancia)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pag
     * @param tipo
     * @param clave
     * @return
     *     returns publisher.Coleccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerProducto/buscarProdRequest", output = "http://Publisher/PVerProducto/buscarProdResponse")
    public Coleccion buscarProd(
        @WebParam(name = "Clave", partName = "Clave")
        String clave,
        @WebParam(name = "Pag", partName = "Pag")
        int pag,
        @WebParam(name = "Tipo", partName = "Tipo")
        int tipo);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerProducto/reservarSesionRequest", output = "http://Publisher/PVerProducto/reservarSesionResponse")
    public int reservarSesion();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Publisher/PVerProducto/stopRequest", output = "http://Publisher/PVerProducto/stopResponse")
    public void stop();

}
