
package publisher;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PVerInfoClienteService", targetNamespace = "http://Publisher/", wsdlLocation = "http://localhost:20016/PIC?wsdl")
public class PVerInfoClienteService
    extends Service
{

    private final static URL PVERINFOCLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException PVERINFOCLIENTESERVICE_EXCEPTION;
    private final static QName PVERINFOCLIENTESERVICE_QNAME = new QName("http://Publisher/", "PVerInfoClienteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20016/PIC?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PVERINFOCLIENTESERVICE_WSDL_LOCATION = url;
        PVERINFOCLIENTESERVICE_EXCEPTION = e;
    }

    public PVerInfoClienteService() {
        super(__getWsdlLocation(), PVERINFOCLIENTESERVICE_QNAME);
    }

    public PVerInfoClienteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PVERINFOCLIENTESERVICE_QNAME, features);
    }

    public PVerInfoClienteService(URL wsdlLocation) {
        super(wsdlLocation, PVERINFOCLIENTESERVICE_QNAME);
    }

    public PVerInfoClienteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PVERINFOCLIENTESERVICE_QNAME, features);
    }

    public PVerInfoClienteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PVerInfoClienteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PVerInfoCliente
     */
    @WebEndpoint(name = "PVerInfoClientePort")
    public PVerInfoCliente getPVerInfoClientePort() {
        return super.getPort(new QName("http://Publisher/", "PVerInfoClientePort"), PVerInfoCliente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PVerInfoCliente
     */
    @WebEndpoint(name = "PVerInfoClientePort")
    public PVerInfoCliente getPVerInfoClientePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publisher/", "PVerInfoClientePort"), PVerInfoCliente.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PVERINFOCLIENTESERVICE_EXCEPTION!= null) {
            throw PVERINFOCLIENTESERVICE_EXCEPTION;
        }
        return PVERINFOCLIENTESERVICE_WSDL_LOCATION;
    }

}
