
package publisher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PAccesoSitio", targetNamespace = "http://Publisher/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PAccesoSitio {


    /**
     * 
     * @param os
     * @param browser
     * @param user
     * @param url
     * @param ip
     */
    @WebMethod
    @Action(input = "http://Publisher/PAccesoSitio/regitrarAccesoRequest", output = "http://Publisher/PAccesoSitio/regitrarAccesoResponse")
    public void regitrarAcceso(
        @WebParam(name = "Ip", partName = "Ip")
        String ip,
        @WebParam(name = "User", partName = "User")
        String user,
        @WebParam(name = "URL", partName = "URL")
        String url,
        @WebParam(name = "Browser", partName = "Browser")
        String browser,
        @WebParam(name = "OS", partName = "OS")
        String os);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Publisher/PAccesoSitio/stopRequest", output = "http://Publisher/PAccesoSitio/stopResponse")
    public void stop();

}
