
package publisher;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PAccesoSitioService", targetNamespace = "http://Publisher/", wsdlLocation = "http://localhost:20016/PAS?wsdl")
public class PAccesoSitioService
    extends Service
{

    private final static URL PACCESOSITIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PACCESOSITIOSERVICE_EXCEPTION;
    private final static QName PACCESOSITIOSERVICE_QNAME = new QName("http://Publisher/", "PAccesoSitioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20016/PAS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PACCESOSITIOSERVICE_WSDL_LOCATION = url;
        PACCESOSITIOSERVICE_EXCEPTION = e;
    }

    public PAccesoSitioService() {
        super(__getWsdlLocation(), PACCESOSITIOSERVICE_QNAME);
    }

    public PAccesoSitioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PACCESOSITIOSERVICE_QNAME, features);
    }

    public PAccesoSitioService(URL wsdlLocation) {
        super(wsdlLocation, PACCESOSITIOSERVICE_QNAME);
    }

    public PAccesoSitioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PACCESOSITIOSERVICE_QNAME, features);
    }

    public PAccesoSitioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PAccesoSitioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PAccesoSitio
     */
    @WebEndpoint(name = "PAccesoSitioPort")
    public PAccesoSitio getPAccesoSitioPort() {
        return super.getPort(new QName("http://Publisher/", "PAccesoSitioPort"), PAccesoSitio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PAccesoSitio
     */
    @WebEndpoint(name = "PAccesoSitioPort")
    public PAccesoSitio getPAccesoSitioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publisher/", "PAccesoSitioPort"), PAccesoSitio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PACCESOSITIOSERVICE_EXCEPTION!= null) {
            throw PACCESOSITIOSERVICE_EXCEPTION;
        }
        return PACCESOSITIOSERVICE_WSDL_LOCATION;
    }

}
