
package publisher;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PAgregarProductoService", targetNamespace = "http://Publisher/", wsdlLocation = "http://localhost:20016/PAP?wsdl")
public class PAgregarProductoService
    extends Service
{

    private final static URL PAGREGARPRODUCTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAGREGARPRODUCTOSERVICE_EXCEPTION;
    private final static QName PAGREGARPRODUCTOSERVICE_QNAME = new QName("http://Publisher/", "PAgregarProductoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20016/PAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAGREGARPRODUCTOSERVICE_WSDL_LOCATION = url;
        PAGREGARPRODUCTOSERVICE_EXCEPTION = e;
    }

    public PAgregarProductoService() {
        super(__getWsdlLocation(), PAGREGARPRODUCTOSERVICE_QNAME);
    }

    public PAgregarProductoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAGREGARPRODUCTOSERVICE_QNAME, features);
    }

    public PAgregarProductoService(URL wsdlLocation) {
        super(wsdlLocation, PAGREGARPRODUCTOSERVICE_QNAME);
    }

    public PAgregarProductoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAGREGARPRODUCTOSERVICE_QNAME, features);
    }

    public PAgregarProductoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PAgregarProductoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PAgregarProducto
     */
    @WebEndpoint(name = "PAgregarProductoPort")
    public PAgregarProducto getPAgregarProductoPort() {
        return super.getPort(new QName("http://Publisher/", "PAgregarProductoPort"), PAgregarProducto.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PAgregarProducto
     */
    @WebEndpoint(name = "PAgregarProductoPort")
    public PAgregarProducto getPAgregarProductoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publisher/", "PAgregarProductoPort"), PAgregarProducto.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAGREGARPRODUCTOSERVICE_EXCEPTION!= null) {
            throw PAGREGARPRODUCTOSERVICE_EXCEPTION;
        }
        return PAGREGARPRODUCTOSERVICE_WSDL_LOCATION;
    }

}
