
package publisher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PAltaUsuario", targetNamespace = "http://Publisher/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PAltaUsuario {


    /**
     * 
     * @param dataU
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PAltaUsuario/ingresarDataUsuarioRequest", output = "http://Publisher/PAltaUsuario/ingresarDataUsuarioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PAltaUsuario/ingresarDataUsuario/Fault/Exception")
    })
    public int ingresarDataUsuario(
        @WebParam(name = "dataU", partName = "dataU")
        DataUsuario dataU)
        throws Exception_Exception
    ;

    /**
     * 
     * @param numeroInstancia
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Publisher/PAltaUsuario/altaUsuarioRequest", output = "http://Publisher/PAltaUsuario/altaUsuarioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PAltaUsuario/altaUsuario/Fault/Exception")
    })
    public void altaUsuario(
        @WebParam(name = "NumeroInstancia", partName = "NumeroInstancia")
        int numeroInstancia)
        throws Exception_Exception
    ;

    /**
     * 
     * @param mail
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PAltaUsuario/verificarMailRequest", output = "http://Publisher/PAltaUsuario/verificarMailResponse")
    public boolean verificarMail(
        @WebParam(name = "mail", partName = "mail")
        String mail);

    /**
     * 
     * @param nickname
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PAltaUsuario/verificarNicknameRequest", output = "http://Publisher/PAltaUsuario/verificarNicknameResponse")
    public boolean verificarNickname(
        @WebParam(name = "Nickname", partName = "Nickname")
        String nickname);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Publisher/PAltaUsuario/stopRequest", output = "http://Publisher/PAltaUsuario/stopResponse")
    public void stop();

}
