
package publisher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PBuscarCategoria", targetNamespace = "http://Publisher/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PBuscarCategoria {


    /**
     * 
     * @return
     *     returns publisher.DataCategoria
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PBuscarCategoria/listarCategoriasRequest", output = "http://Publisher/PBuscarCategoria/listarCategoriasResponse")
    public DataCategoria listarCategorias();

    /**
     * 
     * @param nCat
     * @return
     *     returns publisher.DataCategoria
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PBuscarCategoria/buscarCategoriaRequest", output = "http://Publisher/PBuscarCategoria/buscarCategoriaResponse")
    public DataCategoria buscarCategoria(
        @WebParam(name = "nCat", partName = "nCat")
        String nCat);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Publisher/PBuscarCategoria/stopRequest", output = "http://Publisher/PBuscarCategoria/stopResponse")
    public void stop();

}
