
package publisher;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PReclamoService", targetNamespace = "http://Publisher/", wsdlLocation = "http://localhost:20016/PRP?wsdl")
public class PReclamoService
    extends Service
{

    private final static URL PRECLAMOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRECLAMOSERVICE_EXCEPTION;
    private final static QName PRECLAMOSERVICE_QNAME = new QName("http://Publisher/", "PReclamoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20016/PRP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRECLAMOSERVICE_WSDL_LOCATION = url;
        PRECLAMOSERVICE_EXCEPTION = e;
    }

    public PReclamoService() {
        super(__getWsdlLocation(), PRECLAMOSERVICE_QNAME);
    }

    public PReclamoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRECLAMOSERVICE_QNAME, features);
    }

    public PReclamoService(URL wsdlLocation) {
        super(wsdlLocation, PRECLAMOSERVICE_QNAME);
    }

    public PReclamoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRECLAMOSERVICE_QNAME, features);
    }

    public PReclamoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PReclamoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PReclamo
     */
    @WebEndpoint(name = "PReclamoPort")
    public PReclamo getPReclamoPort() {
        return super.getPort(new QName("http://Publisher/", "PReclamoPort"), PReclamo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PReclamo
     */
    @WebEndpoint(name = "PReclamoPort")
    public PReclamo getPReclamoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publisher/", "PReclamoPort"), PReclamo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRECLAMOSERVICE_EXCEPTION!= null) {
            throw PRECLAMOSERVICE_EXCEPTION;
        }
        return PRECLAMOSERVICE_WSDL_LOCATION;
    }

}
