
package publisher;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PVerProductoService", targetNamespace = "http://Publisher/", wsdlLocation = "http://localhost:20016/PVP?wsdl")
public class PVerProductoService
    extends Service
{

    private final static URL PVERPRODUCTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PVERPRODUCTOSERVICE_EXCEPTION;
    private final static QName PVERPRODUCTOSERVICE_QNAME = new QName("http://Publisher/", "PVerProductoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20016/PVP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PVERPRODUCTOSERVICE_WSDL_LOCATION = url;
        PVERPRODUCTOSERVICE_EXCEPTION = e;
    }

    public PVerProductoService() {
        super(__getWsdlLocation(), PVERPRODUCTOSERVICE_QNAME);
    }

    public PVerProductoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PVERPRODUCTOSERVICE_QNAME, features);
    }

    public PVerProductoService(URL wsdlLocation) {
        super(wsdlLocation, PVERPRODUCTOSERVICE_QNAME);
    }

    public PVerProductoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PVERPRODUCTOSERVICE_QNAME, features);
    }

    public PVerProductoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PVerProductoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PVerProducto
     */
    @WebEndpoint(name = "PVerProductoPort")
    public PVerProducto getPVerProductoPort() {
        return super.getPort(new QName("http://Publisher/", "PVerProductoPort"), PVerProducto.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PVerProducto
     */
    @WebEndpoint(name = "PVerProductoPort")
    public PVerProducto getPVerProductoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publisher/", "PVerProductoPort"), PVerProducto.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PVERPRODUCTOSERVICE_EXCEPTION!= null) {
            throw PVERPRODUCTOSERVICE_EXCEPTION;
        }
        return PVERPRODUCTOSERVICE_WSDL_LOCATION;
    }

}
