
package publisher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PVerInfoProveedor", targetNamespace = "http://Publisher/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PVerInfoProveedor {


    /**
     * 
     * @return
     *     returns publisher.Coleccion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerInfoProveedor/listarProveedoresRequest", output = "http://Publisher/PVerInfoProveedor/listarProveedoresResponse")
    public Coleccion listarProveedores();

    /**
     * 
     * @param nick
     * @param numeroSesion
     * @return
     *     returns publisher.DataProveedor
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerInfoProveedor/seleccionarProveedorRequest", output = "http://Publisher/PVerInfoProveedor/seleccionarProveedorResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PVerInfoProveedor/seleccionarProveedor/Fault/Exception")
    })
    public DataProveedor seleccionarProveedor(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion)
        throws Exception_Exception
    ;

    /**
     * 
     * @param numeroSesion
     * @return
     *     returns publisher.Coleccion
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerInfoProveedor/listarProductosProveedorRequest", output = "http://Publisher/PVerInfoProveedor/listarProductosProveedorResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Publisher/PVerInfoProveedor/listarProductosProveedor/Fault/Exception")
    })
    public Coleccion listarProductosProveedor(
        @WebParam(name = "NumeroSesion", partName = "NumeroSesion")
        int numeroSesion)
        throws Exception_Exception
    ;

    /**
     * 
     * @param proveedor
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerInfoProveedor/isOnlineRequest", output = "http://Publisher/PVerInfoProveedor/isOnlineResponse")
    public boolean isOnline(
        @WebParam(name = "Proveedor", partName = "Proveedor")
        String proveedor);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publisher/PVerInfoProveedor/reservarSesionRequest", output = "http://Publisher/PVerInfoProveedor/reservarSesionResponse")
    public int reservarSesion();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Publisher/PVerInfoProveedor/stopRequest", output = "http://Publisher/PVerInfoProveedor/stopResponse")
    public void stop();

}
