
package publisher;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PVerInfoProveedorService", targetNamespace = "http://Publisher/", wsdlLocation = "http://localhost:20016/PIP?wsdl")
public class PVerInfoProveedorService
    extends Service
{

    private final static URL PVERINFOPROVEEDORSERVICE_WSDL_LOCATION;
    private final static WebServiceException PVERINFOPROVEEDORSERVICE_EXCEPTION;
    private final static QName PVERINFOPROVEEDORSERVICE_QNAME = new QName("http://Publisher/", "PVerInfoProveedorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20016/PIP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PVERINFOPROVEEDORSERVICE_WSDL_LOCATION = url;
        PVERINFOPROVEEDORSERVICE_EXCEPTION = e;
    }

    public PVerInfoProveedorService() {
        super(__getWsdlLocation(), PVERINFOPROVEEDORSERVICE_QNAME);
    }

    public PVerInfoProveedorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PVERINFOPROVEEDORSERVICE_QNAME, features);
    }

    public PVerInfoProveedorService(URL wsdlLocation) {
        super(wsdlLocation, PVERINFOPROVEEDORSERVICE_QNAME);
    }

    public PVerInfoProveedorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PVERINFOPROVEEDORSERVICE_QNAME, features);
    }

    public PVerInfoProveedorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PVerInfoProveedorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PVerInfoProveedor
     */
    @WebEndpoint(name = "PVerInfoProveedorPort")
    public PVerInfoProveedor getPVerInfoProveedorPort() {
        return super.getPort(new QName("http://Publisher/", "PVerInfoProveedorPort"), PVerInfoProveedor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PVerInfoProveedor
     */
    @WebEndpoint(name = "PVerInfoProveedorPort")
    public PVerInfoProveedor getPVerInfoProveedorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publisher/", "PVerInfoProveedorPort"), PVerInfoProveedor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PVERINFOPROVEEDORSERVICE_EXCEPTION!= null) {
            throw PVERINFOPROVEEDORSERVICE_EXCEPTION;
        }
        return PVERINFOPROVEEDORSERVICE_WSDL_LOCATION;
    }

}
