Todo: Build LabP4

Accion: Accion.cpp Accion.h
	g++ -c Accion.cpp -Wall -o Accion.o

aCrear: aCrear.cpp aCrear.h
	g++ -c aCrear.cpp -Wall -o aCrear.o

aDescargar: aDescargar.cpp aDescargar.h
	g++ -c aDescargar.cpp -Wall -o aDescargar.o

aModificar: aModificar.cpp aModificar.h
	g++ -c aModificar.cpp -Wall -o aModificar.o

Archivo: Archivo.cpp Archivo.h
	g++ -c Archivo.cpp -Wall -o Archivo.o

Carpeta: Carpeta.cpp Carpeta.h
	g++ -c Carpeta.cpp -Wall -o Carpeta.o

Recurso: Recurso.cpp Recurso.h
	g++ -c Recurso.cpp -Wall -o Recurso.o

Cargar: Cargar.cpp Cargar.h
	g++ -c Cargar.cpp -Wall -o Cargar.o

Factory: Factory.cpp Factory.h
	g++ -c Factory.cpp -Wall -o Factory.o

Comentario: Comentario.cpp Comentario.h
	g++ -c Comentario.cpp -Wall -o Comentario.o

Main: main.cpp
	g++ -c main.cpp -Wall -o main.o

Notificacion: Notificacion.cpp Notificacion.h
	g++ -c Notificacion.cpp -Wall -o Notificacion.o

Presentacion: Presentacion.cpp Presentacion.h
	g++ -c Presentacion.cpp -Wall -o Presentacion.o

UsuarioCarpeta: UsuarioCarpeta.cpp UsuarioCarpeta.h
	g++ -c UsuarioCarpeta.cpp -Wall -o UsuarioCarpeta.o

Usuario: Usuario.cpp Usuario.h
	g++ -c Usuario.cpp -Wall -o Usuario.o

Utils: Utils.cpp Utils.h
	g++ -c Utils.cpp -Wall -o Utils.o

DataRecurso: DataRecurso.cpp DataRecurso.h
	g++ -c DataRecurso.cpp -Wall -o DataRecurso.o

DataUsuario: DataUsuario.cpp DataUsuario.h
	g++ -c DataUsuario.cpp -Wall -o DataUsuario.o

DataAccion: DataAccion.cpp DataAccion.h
	g++ -c DataAccion.cpp -Wall -o DataAccion.o

DataComentario: DataComentario.cpp DataComentario.h
	g++ -c DataComentario.cpp -Wall -o DataComentario.o

DataNotificacion: DataNotificacion.cpp DataNotificacion.h
	g++ -c DataNotificacion.cpp -Wall -o DataNotificacion.o

DateTime: DateTime.cpp DateTime.h
	g++ -c DateTime.cpp -Wall -o DateTime.o

cAgregarColaborador: cAgregarColaborador.cpp cAgregarColaborador.h
	g++ -c cAgregarColaborador.cpp -Wall -o cAgregarColaborador.o

cAltaUsuario: cAltaUsuario.cpp cAltaUsuario.h
	g++ -c cAltaUsuario.cpp -Wall -o cAltaUsuario.o

cCrearRecurso: cCrearRecurso.cpp cCrearRecurso.h
	g++ -c cCrearRecurso.cpp -Wall -o cCrearRecurso.o

cIngresarComentario: cIngresarComentario.cpp cIngresarComentario.h 
	g++ -c cIngresarComentario.cpp -Wall -o cIngresarComentario.o

cModificarArchivo: cModificarArchivo.cpp cModificarArchivo.h
	g++ -c cModificarArchivo.cpp -Wall -o cModificarArchivo.o

cSuscripcion: cSuscripcion.cpp cSuscripcion.h
	g++ -c cSuscripcion.cpp -Wall -o cSuscripcion.o

cVerInfoArchivo: cVerInfoArchivo.cpp cVerInfoArchivo.h 
	g++ -c cVerInfoArchivo.cpp -Wall -o cVerInfoArchivo.o

cVerInfoCarpeta: cVerInfoCarpeta.cpp cVerInfoCarpeta.h 
	g++ -c cVerInfoCarpeta.cpp -Wall -o cVerInfoCarpeta.o

cVerInfoUsuario: cVerInfoUsuario.cpp cVerInfoUsuario.h 
	g++ -c cVerInfoUsuario.cpp -Wall -o cVerInfoUsuario.o

Build:Accion aCrear aDescargar aModificar Archivo Carpeta Recurso Cargar Factory Comentario Main Notificacion Presentacion UsuarioCarpeta Usuario Utils DataRecurso DataUsuario DataAccion DataComentario DataNotificacion DateTime cAgregarColaborador cAltaUsuario cCrearRecurso cIngresarComentario cModificarArchivo cSuscripcion cVerInfoArchivo cVerInfoCarpeta cVerInfoUsuario
	g++ Accion.o aCrear.o aDescargar.o aModificar.o Archivo.o Carpeta.o Recurso.o Cargar.o Factory.o Comentario.o main.o Notificacion.o Presentacion.o UsuarioCarpeta.o Usuario.o Utils.o DataUsuario.o DataAccion.o DataComentario.o DataNotificacion.o DateTime.o DataRecurso.o cAgregarColaborador.o cAltaUsuario.o cCrearRecurso.o cIngresarComentario.o cModificarArchivo.o cSuscripcion.o cVerInfoArchivo.o cVerInfoCarpeta.o cVerInfoUsuario.o -o LabP4

Clear: 
	rm *.o 
